/* eslint-disable @next/next/no-img-element -- self-hosted venue photography for the static build */
import { BrandLockup } from "./brand-lockup";

const BASE_PATH = import.meta.env.BASE_URL.endsWith("/") ? import.meta.env.BASE_URL : `${import.meta.env.BASE_URL}/`;
const sitePath = (path = "") => `${BASE_PATH}${path.replace(/^\/+/, "")}`;
const MAPS_URL = "https://www.google.com/maps/place/A%5CMaze:+Escape+Game+Old+Port/@45.5027813,-73.5603544,17z/data=!3m1!4b1!4m6!3m5!1s0x4cc91b14b4dabe19:0x895ec0f0dc0294de!8m2!3d45.5027776!4d-73.5577795!16s%2Fg%2F11fst7nf7c";
type Locale = "en" | "fr";
export type ContentMode = "bar" | "menu" | "games" | "faq";

const routePairs: Record<ContentMode, [string, string]> = {
  bar: ["cocktail-bar-old-montreal/", "fr/bar-a-cocktails-vieux-montreal/"],
  menu: ["menu/", "fr/menu/"], games: ["escape-games/", "fr/jeux-evasion/"], faq: ["faq/", "fr/faq/"],
};

const cocktailItems = [
  ["The Science Experiment", "L’Expérience scientifique", "$16", "Mezcal · Aperol · lime · soda · absinthe", "Mezcal · Aperol · lime · soda · absinthe"],
  ["Oscillator", "Oscillateur", "$16", "Canadian rye · chocolate · butterscotch · Chartreuse · chili", "Seigle canadien · chocolat · butterscotch · Chartreuse · chili"],
  ["Tesla’s Carré", "Carré Tesla", "$17", "Rye · Grand Marnier · sweet vermouth · Bénédictine · smoke", "Seigle · Grand Marnier · vermouth doux · Bénédictine · fumée"],
  ["Radioactive Sour", "Sour radioactif", "$16", "White rum · Midori · lemon · foamer", "Rhum blanc · Midori · citron · agent moussant"],
  ["Wardenclyff", "Wardenclyff", "$16", "Calvados · amaro · red vermouth · Angostura · smoke bubble", "Calvados · amaro · vermouth rouge · Angostura · bulle de fumée"],
  ["Alternating Current", "Courant alternatif", "$15", "Gin · Grand Marnier · cardamom · butterfly-pea tea", "Gin · Grand Marnier · cardamome · thé de pois papillon"],
  ["Fire Conductor", "Conducteur de feu", "$15", "Whisky · lime · maple · ginger beer", "Whisky · lime · érable · bière de gingembre"],
  ["Cocktail of the Season", "Cocktail de la saison", "$17", "Ask the bartender for the current creation", "Demandez la création du moment"],
];

const faqItems = [
  ["Can I come without playing an escape game?", "Puis-je venir sans faire de jeu d’évasion?", "Yes. Inventions is a cocktail bar in its own right. Come for drinks and small plates; a game is completely optional.", "Oui. Inventions est un bar à cocktails à part entière. Venez pour boire et manger; le jeu est entièrement facultatif."],
  ["Do I need a reservation?", "Faut-il réserver?", "Walk-ins are welcome when space is available. Contact the team in advance for a group or private event.", "Les visites spontanées sont bienvenues selon les places. Contactez l’équipe à l’avance pour un groupe ou une privatisation."],
  ["Do you accept walk-ins?", "Acceptez-vous les visites spontanées?", "Yes, subject to available seating and private events.", "Oui, selon les places disponibles et les événements privés."],
  ["Where is the entrance?", "Où se trouve l’entrée?", "Enter A\\Maze Old Port at 480 Rue Saint-Jean in Old Montreal; Inventions is inside the venue.", "Entrez chez A\\Maze Vieux-Port au 480, rue Saint-Jean dans le Vieux-Montréal; Inventions se trouve à l’intérieur."],
  ["What are the bar hours?", "Quelles sont les heures du bar?", "The current published hours are Monday–Friday, 2 pm–11 pm; Saturday–Sunday, 10 am–11 pm. Hours may change for holidays or private events.", "Les heures publiées sont du lundi au vendredi, de 14 h à 23 h; samedi et dimanche, de 10 h à 23 h. Elles peuvent changer lors des jours fériés ou événements privés."],
  ["Can I rent the whole bar?", "Peut-on privatiser tout le bar?", "Yes. Private rental is available for corporate 5 à 7s, birthdays and celebrations, subject to date and group size.", "Oui. La privatisation est offerte pour les 5 à 7, anniversaires et célébrations, selon la date et la taille du groupe."],
  ["Is food available?", "Y a-t-il de la nourriture?", "Yes. The menu includes a concise selection of small plates and snacks.", "Oui. Le menu comprend une courte sélection de bouchées et collations."],
  ["Are there non-alcoholic cocktails?", "Y a-t-il des options sans alcool?", "Yes. Zero-proof drinks, non-alcoholic beer and soft drinks are available.", "Oui. Des boissons sans alcool, une bière sans alcool et des boissons gazeuses sont offertes."],
  ["Is the venue accessible?", "Le lieu est-il accessible?", "The entrance has four steps. Tesla’s Enigmas includes stairs and flashing lights. The outdoor Shipping Empire route is wheelchair accessible and covers more than 1 km.", "L’entrée comporte quatre marches. Les Énigmes de Tesla comprend des escaliers et des lumières clignotantes. Le parcours extérieur Empire maritime est accessible en fauteuil roulant et fait plus de 1 km."],
  ["Can I combine the bar and a game?", "Peut-on combiner le bar et un jeu?", "Yes. Book an escape game separately and visit the bar before or after.", "Oui. Réservez le jeu séparément et passez au bar avant ou après."],
  ["Where can I park?", "Où peut-on stationner?", "Try 508–510 Rue Saint-Jean or the Indigo garage at 230 Rue Saint-Sacrement. Availability and rates are controlled by the operators.", "Essayez le 508–510, rue Saint-Jean ou le stationnement Indigo au 230, rue Saint-Sacrement. Les disponibilités et tarifs dépendent des exploitants."],
];

function PageHeader({ locale, mode }: { locale: Locale; mode: ContentMode }) {
  const isFr = locale === "fr";
  const [enPath, frPath] = routePairs[mode];
  return <header className="team-header content-header"><a className="brand" href={sitePath(isFr ? "fr/" : "")}><BrandLockup locale={locale} compact /></a><nav><a href={sitePath(isFr ? "fr/menu/" : "menu/")}>Menu</a><a href={sitePath(isFr ? "fr/evenements-prives/" : "private-events/")}>{isFr ? "Événements privés" : "Private events"}</a><a href={sitePath(isFr ? "fr/faq/" : "faq/")}>FAQ</a></nav><a className="language-link" href={sitePath(isFr ? enPath : frPath)}>{isFr ? "EN" : "FR"}</a></header>;
}

function PageFooter({ locale }: { locale: Locale }) {
  const isFr = locale === "fr";
  return <footer className="team-footer content-footer"><a href={sitePath(isFr ? "fr/" : "")}>{isFr ? "Retour à l’accueil" : "Back home"} ↖</a><a href="https://www.amazemontreal.com" className="amaze-family"><span>{isFr ? "Une expérience de" : "An experience from"}</span><img src={sitePath("images/amaze-official-logo.webp")} alt="A\\Maze" width="1000" height="203" /></a></footer>;
}

export function ContentPage({ locale = "en", mode }: { locale?: Locale; mode: ContentMode }) {
  const isFr = locale === "fr";
  const headings = {
    bar: [isFr ? "Bar à cocktails dans le Vieux-Montréal" : "Cocktail bar in Old Montreal", isFr ? "Un laboratoire de cocktails inspiré de Nikola Tesla, caché à l’intérieur d’A\\Maze Vieux-Port. Aucun jeu d’évasion requis." : "A Nikola Tesla-inspired cocktail laboratory hidden inside A\\Maze Old Port. No escape game required."],
    menu: [isFr ? "Menu d’Inventions" : "Inventions cocktail menu", isFr ? "Cocktails signatures, boissons sans alcool, vins, bières locales et petites bouchées dans le Vieux-Montréal." : "Signature cocktails, zero-proof drinks, wine, local beer and small plates in Old Montreal."],
    games: [isFr ? "Jeux d’évasion au Vieux-Port" : "Old Port escape games", isFr ? "Trois expériences privées sous le même toit que le bar. Prenez un verre avec ou sans jeu." : "Three private experiences under the same roof as the bar. Come for drinks with or without a game."],
    faq: [isFr ? "Questions fréquentes" : "Frequently asked questions", isFr ? "Tout ce qu’il faut savoir avant de venir chez Inventions par A\\Maze." : "Everything to know before visiting Inventions by A\\Maze."],
  }[mode];

  return <main className="content-page" lang={locale}><PageHeader locale={locale} mode={mode} /><section className="content-hero"><div><p className="eyebrow">Inventions · {isFr ? "Vieux-Montréal" : "Old Montreal"}</p><h1>{headings[0]}</h1><p>{headings[1]}</p><div className="hero-actions"><a className="button button-solid" href={mode === "menu" ? "#full-menu" : mode === "faq" ? "#answers" : MAPS_URL} target={mode === "menu" || mode === "faq" ? undefined : "_blank"} rel={mode === "menu" || mode === "faq" ? undefined : "noreferrer"}>{mode === "menu" ? (isFr ? "Voir le menu" : "View menu") : mode === "faq" ? (isFr ? "Voir les réponses" : "See answers") : (isFr ? "Obtenir l’itinéraire" : "Get directions")}</a><a className="button" href={sitePath(isFr ? "fr/" : "")}>{isFr ? "Découvrir Inventions" : "Explore Inventions"}</a></div></div><img src={sitePath(mode === "games" ? "images/game-tesla.webp" : "images/hero-cocktails.jpg")} alt={mode === "games" ? (isFr ? "Les Énigmes de Tesla" : "Tesla’s Enigmas") : (isFr ? "Cocktails signatures chez Inventions" : "Signature cocktails at Inventions")} width="1800" height="1800" /></section>
    {mode === "bar" && <BarContent locale={locale} />}{mode === "menu" && <MenuContent locale={locale} />}{mode === "games" && <GamesContent locale={locale} />}{mode === "faq" && <FaqContent locale={locale} />}<PageFooter locale={locale} /></main>;
}

function BarContent({ locale }: { locale: Locale }) { const fr = locale === "fr"; return <><section className="content-intro section-shell"><div><p className="eyebrow">{fr ? "Cocktails · Vieux-Montréal · Sans jeu requis" : "Cocktails · Old Montreal · No game required"}</p><h2>{fr ? "Un bar caché, pas une salle d’attente." : "A hidden bar, not a waiting room."}</h2></div><p>{fr ? "Inventions est une destination à part entière. Les recettes s’inspirent des travaux de Tesla; le décor emprunte à l’âge électrique sans tomber dans le steampunk de costume; l’ambiance reste celle d’un bar intime du Vieux-Montréal." : "Inventions is a destination in its own right. Drinks draw from Tesla’s work; the room borrows from the Electric Age without costume steampunk; the experience remains an intimate Old Montreal cocktail bar."}</p></section><section className="content-feature-grid section-shell"><article><span>01</span><h3>{fr ? "Cocktails théâtraux" : "Theatrical cocktails"}</h3><p>{fr ? "Chaque signature lie une technique ou un service à une histoire de Tesla." : "Each signature connects a technique or serve to a Tesla story."}</p></article><article><span>02</span><h3>{fr ? "Visites spontanées" : "Walk-ins welcome"}</h3><p>{fr ? "Venez prendre un verre sans réserver de jeu, selon les places disponibles." : "Come for a drink without booking a game, subject to available space."}</p></article><article><span>03</span><h3>{fr ? "Une équipe expérimentée" : "Experienced operators"}</h3><p>{fr ? "Créé par l’équipe d’A\\Maze Montréal, qui conçoit des expériences immersives depuis 2014." : "Created by the A\\Maze Montréal team, designing immersive experiences since 2014."}</p></article></section></>; }

function MenuContent({ locale }: { locale: Locale }) { const fr = locale === "fr"; return <section className="standalone-menu section-shell" id="full-menu"><div className="standalone-menu-heading"><p className="eyebrow">{fr ? "Menu actuel" : "Current menu"}</p><h2>{fr ? "Cocktails signatures" : "Signature cocktails"}</h2><p>{fr ? "Sélectionnez chaque cocktail sur la page d’accueil pour lire son histoire complète." : "Select any cocktail on the home page to read its complete story."}</p></div><div className="standalone-menu-list">{cocktailItems.map((item, index) => <article key={item[0]}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{fr ? item[1] : item[0]}</h3><p>{fr ? item[4] : item[3]}</p></div><strong>{item[2]}</strong></article>)}</div><div className="menu-summary-grid"><article><h3>{fr ? "Sans alcool" : "Zero proof"}</h3><p>Winnie le Pop $8 · Mikkeller 0% $8 · Shirley Temple $7 · {fr ? "boissons gazeuses" : "soft drinks"} $4</p></article><article><h3>{fr ? "Bières et vins" : "Beer & wine"}</h3><p>{fr ? "Bières locales à partir de 8 $ · vins au verre et à la bouteille · mousseux 200 ml 16 $" : "Local beer from $8 · wine by the glass and bottle · sparkling 200 ml $16"}</p></article><article><h3>{fr ? "Petites bouchées" : "Small bites"}</h3><p>{fr ? "Jerky de poulet 10 $ · noix rôties maison 8 $ · olives ou cornichons 6 $" : "Chicken jerky $10 · house-roasted nuts $8 · olives or pickles $6"}</p></article></div><p className="menu-disclaimer">{fr ? "Prix et disponibilité vérifiés le 20 août 2026; ils peuvent changer. Informez l’équipe de vos allergies." : "Prices and availability checked August 20, 2026; they may change. Tell the team about allergies."}</p></section>; }

function GamesContent({ locale }: { locale: Locale }) { const fr = locale === "fr"; const games = [["Tesla’s Enigmas", "Les Énigmes de Tesla", "2–6 · 60 min · $37", "images/game-tesla.webp"], ["Dead Man’s Chest", "Le coffre du mort", "2–3 · 60 min · $20", "images/game-chest-current.webp"], ["Secrets of a Shipping Empire", "Le secret d’un empire maritime", "2–7 · 60–90 min · $25", "images/game-shipping-current.webp"]]; return <section className="standalone-games section-shell">{games.map((game) => <article key={game[0]}><img src={sitePath(game[3])} alt={fr ? game[1] : game[0]} loading="lazy" width="1000" height="667" /><div><p className="eyebrow">{game[2]}</p><h2>{fr ? game[1] : game[0]}</h2><p>{fr ? "Réservation privée en français ou en anglais. Le bar est disponible avant ou après, mais le jeu n’est jamais requis pour visiter Inventions." : "Private booking in English or French. Visit the bar before or after, but a game is never required to enjoy Inventions."}</p><a className="button" href={fr ? "https://www.amazemontreal.com/fr/jeu-devasion-et-restaurant-vieux-port" : "https://www.amazemontreal.com/old-port-escape-room-restaurant"}>{fr ? "Voir sur A\\Maze" : "View on A\\Maze"}</a></div></article>)}</section>; }

function FaqContent({ locale }: { locale: Locale }) { const fr = locale === "fr"; return <section className="standalone-faq section-shell" id="answers"><div className="faq-list">{faqItems.map((item) => <details key={item[0]}><summary>{fr ? item[1] : item[0]}</summary><p>{fr ? item[3] : item[2]}</p></details>)}</div><div className="faq-contact"><p>{fr ? "Une question qui n’est pas ici?" : "Something not answered here?"}</p><a href="mailto:escape@amazemontreal.com">escape@amazemontreal.com</a><a href={MAPS_URL} target="_blank" rel="noreferrer">{fr ? "Itinéraire Google Maps" : "Google Maps directions"} ↗</a></div></section>; }
